services:
  db:
    image: postgres:15-alpine
    container_name: klubly-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:?Falta la variable DB_NAME en .env}
      POSTGRES_USER: ${DB_USER:?Falta la variable DB_USER en .env}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Falta la variable DB_PASSWORD en .env}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - klubly-network

  backend:
    build: ./backend
    container_name: klubly-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:?Error en DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:?Error en DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:?Error en DB_PASSWORD}
      - APP_JWT_SECRET=${JWT_SECRET:?Falta la variable JWT_SECRET en .env (mínimo 32 caracteres)}
      - APP_DEFAULT_PASSWORD=${APP_DEFAULT_PASSWORD:?Falta la variable APP_DEFAULT_PASSWORD en .env}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop # Recrea todo al iniciar y borra al cerrar
    networks:
      - klubly-network

  frontend:
    build: ./frontend
    container_name: klubly-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - klubly-network

  adminer:
    image: adminer
    container_name: klubly-adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - klubly-network

networks:
  klubly-network:
    name: klubly-network
    driver: bridge

volumes:
  pgdata:
