spring:
  application:
    name: klubly-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/klubly_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_placeholder}
    password: ${SPRING_DATASOURCE_PASSWORD:pass_placeholder}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true

#Configuración del logger
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/klubly.log
  logback:
    rollingpolicy:
      max-file-size: 10MB #Tamaño máximo de cada archivo de log
      max-history: 7 #Días para mantener los archivos de log antiguos
  level:
    root: INFO
    "[com.klubly]": DEBUG

app:
  jwt-secret: ${APP_JWT_SECRET:dispositivo_de_seguridad_jwt_no_configurado}
  jwt-expiration-milliseconds: 3600000
  default-password: ${APP_DEFAULT_PASSWORD:klubly_default_pass}
